version: '3.8'
name: assemble-prod

services:
  frontend:
    env_file:
      - path: ".env.prod"
    build: ./frontend
    container_name: assemble-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - assemble-network

  backend:
    env_file:
      - path: ".env.prod"
    build: ./backend
    container_name: assemble-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      MONGO_URI: ${MONGO_URI}
      POSTGRES_URI: ${POSTGRES_URI}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SUPERUSER_USERNAME: ${SUPERUSER_USERNAME}
      SUPERUSER_PASSWORD: ${SUPERUSER_PASSWORD}
    networks:
      - assemble-network

networks:
  assemble-network: