version: '3.8'
name: assemble-dev

services:
  mongodb:
    image: mongo:7
    container_name: assemble-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
    volumes:
      - mongodb_data:/data/db
    networks:
      - assemble-network

  postgresql:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 5s
      timeout: 5s
      retries: 10
    image: postgres:17.7
    container_name: assemble-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: "assemble"
    volumes:
      - pgdata:/data/db
    networks:
      - assemble-network

volumes:
  mongodb_data:
  pgdata:

networks:
  assemble-network:
