# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
reviews:
  profile: chill
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
  suggested_reviewers: false
  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false
chat:
  integrations:
    jira:
      usage: disabled
    linear:
      usage: disabled
