name: Deploy Backend
on:
  push:
    branches: [ "main", "feature/**" ]

jobs:

  build-backend-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_ASSEMBLE_BACKEND_TAG }}
          context: ./backend

  build-frontend-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_ASSEMBLE_FRONTEND_TAG }}
          context: ./frontend
          build-args: |
            BACKEND_API_URL=${{ secrets.BACKEND_API_URL }}


  deploy-backend-to-render:
    runs-on: ubuntu-latest
    needs: build-backend-image
    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_BACKEND_HOOK }}

  deploy-frontend-to-render:
    runs-on: ubuntu-latest
    needs: build-frontend-image
    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_BACKEND_HOOK }}
