name: Deploy Backend
on:
  push:
    branches: [ "main", "feature/**" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Build Backend
        run: |
          mvn -B -DskipTests -f backend/pom.xml clean package

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v5
        with:
          name: backend.jar
          path: backend/target/backend.jar

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version: 24.12.0

      - name: Install dependencies
        run: |
          npm ci

      - name: Build frontend
        env:
          NODE_ENV: production
          BACKEND_API_URL: ${{ secrets.BACKEND_API_URL }}
        run: |
          npm run orval:generate
          npm run build

      - name: Upload frontend build
        uses: actions/upload-artifact@v5
        with:
          name: frontend
          path: frontend
  
  
  push-backend-to-docker-hub:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v5

      - name: Download Backend Artifact
        uses: actions/download-artifact@v5
        with:
          name: backend.jar
          path: backend/target

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_ASSEMBLE_BACKEND_TAG }}
          context: .

  push-frontend-to-ducker-hub:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v5

      - name: Download frontend build
        uses: actions/download-artifact@v5
        with:
          name: frontend
          path: frontend

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_ASSEMBLE_FRONTEND_TAG }}
          context: .


  deploy-backend-to-render:
    runs-on: ubuntu-latest
    needs: push-backend-to-docker-hub
    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_BACKEND_HOOK }}

  deploy-frontend-to-render:
    runs-on: ubuntu-latest
    needs: push-frontend-to-ducker-hub
    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_BACKEND_HOOK }}
